### PR TITLE
Use new syntax and add new platforms

### PR DESCRIPTION
**Pull request by helgee**
This seems to work, reference is https://github.com/staticfloat/OggBuilder/blob/master/build_tarballs.jl

### CODE REVIEW

**Comment by helgee** [comment]
Let's see whether I will get in answer in https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/32 before merging.

**Comment by bgodard** [comment]
Looking at SundialsBuilder, I think line 18 should use ${prefix}
```
./configure --prefix=${prefix} --host=$target --enable-fortran=no --enable-python=no --disable-static
```

**Comment by bgodard** [comment]
Looking at the travis logs, I have doubts it is actually building anything...

**Comment by helgee** [comment]
It takes 16 minutes, though, and the log for other *Builder repos looks the same, e.g. https://api.travis-ci.org/v3/job/370357940/log.txt

**Comment by helgee** [comment]
I think I will go ahead and merge this, do you have access to a FreeBSD system to check whether the binaries work?

**Comment by bgodard** [comment]
Thank you. 
I have only Linux boxes but when I find the time, I will test the FreeBSD build in a VM.

**Comment by bgodard** [comment]
The install (using the binary) and tests of CALCEPH were successful on FreeBSD (via VirtualBox running in Ubuntu).

**Pull request merged**
