### PR TITLE
Update build_tarballs.jl

### PR DESCRIPTION
**Pull request by bgodard**
Trying to make it work with current BinaryBuilder.

### CODE REVIEW

**Comment by bgodard** [comment]
The build of the tag failed because of a change in BinaryBuilder. I tried to fix it by doing changes similar to what staticfloat did on SundialsBuilder but still it is not working and the error message is not very useful to me.

**Comment by helgee** [comment]
Bizarre. I tried the script in a local VM and it works...

**Comment by helgee** [comment]
Closing in favor of #3

**Comment by bgodard** [comment]
OK I found the problem. I used the github online text editor for this change and there are some special characters in the source which do not show in github online editor...

**Comment by helgee** [comment]
Oh man, this is why can't have nice things 😝

**Pull request closed without merging**
